name: Build and push to ECR

# Build image and push to ECR when code merged to main branch
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1.5.8
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1.3.3
      - name: Build Docker image
        id: docker-build
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: adminka-web
        run: |
          service_version=main-${GITHUB_SHA:0:7}-$(date +%s)
          image=$ECR_REGISTRY/$ECR_REPOSITORY:$service_version
          docker build -t $image -f Dockerfile --build-arg SERVICE_VERSION=$service_version .
          echo "##[set-output name=image;]$image"
      - name: Push Docker image to Amazon ECR
        run: docker push ${{ steps.docker-build.outputs.image }}
      - name: Logout of Amazon ECR
        if: always()
        run: docker logout ${{ steps.login-ecr.outputs.registry }}
